
import React from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import ReactMarkdown from 'react-markdown';

interface ResultSectionProps {
  result: string;
}

export function ResultSection({ result }: ResultSectionProps) {
  // Check if the result contains urgent findings
  const hasUrgentFindings = result.toUpperCase().includes("URGENT");

  return (
    <section id="result" className={cn("animate-in fade-in duration-700 rounded-lg border", 
      hasUrgentFindings ? "border-destructive/30" : "border-border")}>
      <Card className={cn("border-none shadow-none",
        hasUrgentFindings ? "bg-destructive/5" : "")}>
        <CardHeader className={cn(
          hasUrgentFindings ? "border-b border-destructive/30" : "border-b")}>
          <CardTitle className="flex items-center gap-2">
            {hasUrgentFindings && (
              <span className="inline-flex h-6 w-6 items-center justify-center rounded-full bg-destructive/20 text-destructive text-sm">!</span>
            )}
            Analysis Results
          </CardTitle>
          <CardDescription>
            {hasUrgentFindings 
              ? "Attention: This analysis contains potentially urgent findings." 
              : "Review the AI analysis of the uploaded medical image."}
          </CardDescription>
        </CardHeader>
        <CardContent className="p-6">
          <div className="prose prose-stone max-w-none dark:prose-invert">
            <ReactMarkdown>
              {result}
            </ReactMarkdown>
          </div>
          
          <div className="mt-6 rounded-md bg-muted/50 p-4 text-sm text-muted-foreground">
            <strong>Disclaimer:</strong> This analysis is generated by AI and is intended for educational purposes only. 
            Always consult with a qualified healthcare professional for accurate diagnosis and treatment options.
          </div>
        </CardContent>
      </Card>
    </section>
  );
}
